/* Nội dung mặc định – admin có thể sửa, lưu trong trình duyệt (localStorage) */
window.CMS_DEFAULT = {
  "meta.title": "Tour Lào – Cao Nguyên Bolaven 4N3Đ | VietKite Travel",

  "nav.logo": "https://vietkite.com.vn/wp-content/uploads/2024/12/logo-cty-canh-dieu-viet-vietkite.jpg",
  "nav.link1": "Điểm Nổi Bật",
  "nav.link2": "Hình Ảnh",
  "nav.link3": "Lịch Trình",
  "nav.link4": "Giá Tour",
  "nav.link5": "Đặt Tour",
  "nav.cta": "🌏 Đặt Ngay",
  "nav.mob1": "Điểm Nổi Bật",
  "nav.mob2": "Hình Ảnh",
  "nav.mob3": "Lịch Trình",
  "nav.mob4": "Giá Tour",
  "nav.mob5": "🌏 Đặt Tour Ngay",

  "hero.bg": "https://datviettour.com.vn/uploads/images/tin-tuc-SEO-NN-chau-a/lao/danh-thang/bolaven-thoi-diem-dep-nhat.jpeg",
  "hero.badge": "✈ Khởi hành hàng tuần từ TP.HCM",
  "hero.title": "Lào –<br><span>Cao Nguyên Bolaven</span><br>4 Ngày 3 Đêm",
  "hero.sub": "Xứ sở cà phê thượng hạng • Thác Tad Fane hùng vĩ • Di sản UNESCO Wat Phou • Làng dân tộc Katu độc đáo",
  "hero.stat1.val": "4N3Đ",
  "hero.stat1.lbl": "Ngày khám phá",
  "hero.stat2.val": "3",
  "hero.stat2.lbl": "Quốc gia",
  "hero.stat3.val": "7.65M₫",
  "hero.stat3.lbl": "Từ / khách",
  "hero.stat4.val": "4★",
  "hero.stat4.lbl": "Khách sạn",
  "hero.btn1": "🎒 Đặt Tour Ngay",
  "hero.btn2": "Xem Lịch Trình",
  "hero.scroll": "Khám phá",

  "trust.1.val": "15+",
  "trust.1.lbl": "Năm kinh nghiệm",
  "trust.2.val": "50K+",
  "trust.2.lbl": "Khách hài lòng",
  "trust.3.val": "200M₫",
  "trust.3.lbl": "BH tối đa / khách",
  "trust.4.val": "4★",
  "trust.4.lbl": "Khách sạn",
  "trust.5.val": "10+",
  "trust.5.lbl": "Điểm tham quan",

  "hl.label": "Điểm nổi bật",
  "hl.title": "Trải nghiệm độc đáo chỉ có ở tour này",
  "hl.sub": "Cao nguyên Bolaven – thiên đường cà phê và thác nước kỳ vĩ của miền Nam nước Lào",
  "hl.1.img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tad_Fane_waterfall%2C_Laos.jpg/1280px-Tad_Fane_waterfall%2C_Laos.jpg",
  "hl.1.title": "🌊 Thác Tad Fane",
  "hl.1.text": "Thác đôi hùng vĩ được ví như mái tóc người con gái Nam Lào – nơi tổ chức zipline, leo núi, cà phê miễn phí.",
  "hl.2.img": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Tad_Hang_waterfalls%2C_Tad_Lo_village%2C_Bolaven_Plateau%2C_Laos.jpg",
  "hl.2.title": "💧 Thác Nhương & Tad Lo",
  "hl.2.text": "Thác Tad Yuang, Tad Lo và Tad Hang – hệ thống thác nước đẹp nhất miền Nam Lào bên hạ nguồn sông Mekong.",
  "hl.3.img": "https://redsvn.net/wp-content/uploads/2099/05/Wat-Phou-05.jpg",
  "hl.3.title": "🏛️ Wat Phou – Di sản UNESCO",
  "hl.3.text": "Quần thể đền Khmer thế kỷ VI – di sản văn hoá thế giới với kiến trúc đền đài mang đậm phong cách Khmer cổ kính.",
  "hl.4.img": "https://datviettour.com.vn/uploads/images/tin-tuc-SEO-NN-chau-a/lao/danh-thang/bolaven-thoi-diem-dep-nhat.jpeg",
  "hl.4.title": "☕ Paksong – Cà Phê Thượng Hạng",
  "hl.4.text": "Trang trại cà phê truyền thống trên cao nguyên 1.000–1.350m – thưởng thức Paksong Highland Coffee giữa mây mù.",

  "gal.label": "Hình ảnh",
  "gal.title": "Khoảnh khắc đáng nhớ",
  "gal.1.img": "https://datviettour.com.vn/uploads/images/tin-tuc-SEO-NN-chau-a/lao/danh-thang/bolaven-thoi-diem-dep-nhat.jpeg",
  "gal.1.cap": "Cao nguyên Bolaven – Thiên đường xanh",
  "gal.2.img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tad_Fane_waterfall%2C_Laos.jpg/1280px-Tad_Fane_waterfall%2C_Laos.jpg",
  "gal.2.cap": "Thác Tad Fane hùng vĩ",
  "gal.3.img": "https://redsvn.net/wp-content/uploads/2099/05/Wat-Phou-05.jpg",
  "gal.3.cap": "Wat Phou – UNESCO",
  "gal.4.img": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Tad_Hang_waterfalls%2C_Tad_Lo_village%2C_Bolaven_Plateau%2C_Laos.jpg",
  "gal.4.cap": "Thác Tad Hang – Tad Lo",
  "gal.5.img": "https://images.trvl-media.com/place/2815/dd7a1c5d-8836-41a9-973b-11f19a4a4f09.jpg",
  "gal.5.cap": "Thành phố Pakse – Bờ Mekong",

  "itin.label": "Chương trình",
  "itin.title": "Lịch trình chi tiết 4 ngày 3 đêm",
  "itin.sub": "Mỗi ngày là một hành trình khám phá mới, sắp xếp tối ưu để bạn tận hưởng trọn vẹn.",
  "day1.img": "https://vietkite.com.vn/wp-content/uploads/2024/12/thac-khone-phapheng-lao.jpg",
  "day1.title": "TP.HỒ CHÍ MINH → CAMPUCHIA → LÀO",
  "day1.route": "HCM 🚌 Xa Mát (Tây Ninh) → Kratier → Pakse",
  "day1.meals": "🌅 Điểm tâm sáng|🍜 Cơm trưa Kratier|🍽️ Cơm tối Pakse",
  "day1.acts": "04h00 – Xe và hướng dẫn đón khách tại điểm hẹn, khởi hành đi Lào qua cửa khẩu Xa Mát (Tây Ninh)|Làm thủ tục xuất cảnh VN, nhập cảnh Campuchia|Dùng cơm trưa tại <strong>Kratier</strong>, tiếp tục khởi hành đến Pakse – Thành phố lớn thứ 3 của Lào|Tham quan <strong>Thác Khone Phapheng</strong> – thác nước lớn nhất Đông Nam Á trên sông Mekong|Về Pakse, thưởng thức đặc sản Lào: <strong>xôi, thịt nướng, cá nướng, món Lạp (gỏi đu đủ)</strong>|🏨 Nghỉ đêm tại khách sạn 4★ Pakse",
  "day2.img": "https://vietkite.com.vn/wp-content/uploads/2024/12/thac-tad-fane-bolaven-lao.jpg",
  "day2.title": "PAKSE – PAKSONG – CAO NGUYÊN BOLAVEN",
  "day2.route": "Pakse → Paksong → Tad Fane → Tad Yuang → Tad Lo",
  "day2.meals": "🥐 Buffet sáng KS|🍜 Cơm trưa địa phương|🍽️ Cơm tối Pakse",
  "day2.acts": "Buffet sáng tại khách sạn, khởi hành đến <strong>Cao nguyên Bolaven</strong> (1.000–1.350m)|Dừng chân thưởng thức cà phê sáng tại <strong>Paksong Highland Coffee</strong>|Tham quan <strong>Thác Tad Fane</strong> – thác đôi hùng vĩ|Chiêm ngưỡng <strong>Thác Nhương (Tad Yuang)</strong>|Tham quan <strong>Thác Tad Lo và Tad Hang</strong>|Buổi tối: Trải nghiệm văn hoá tại <strong>Làng dân tộc Katu</strong>|🏨 Nghỉ đêm tại Pakse",
  "day3.img": "https://vietkite.com.vn/wp-content/uploads/2024/12/wat-phou-lao-unesco.jpg",
  "day3.title": "CAO NGUYÊN BOLAVEN – WAT PHOU – PAKSE",
  "day3.route": "Pakse → Chợ Dao Hueng → Wat Phou → Chùa Luang → Phusalau",
  "day3.meals": "🥐 Buffet sáng KS|🍜 Cơm trưa nhà hàng|🍽️ Cơm tối Pakse",
  "day3.acts": "Buffet sáng tại khách sạn, làm thủ tục trả phòng|Tham quan <strong>Wat Phou</strong> – Di sản văn hoá UNESCO|Dùng cơm trưa tại nhà hàng|Mua sắm tại <strong>Chợ Dao Hueng</strong>|<strong>Chùa Luang</strong> – một trong những chùa đẹp nhất Pakse|Viếng thăm <strong>Chùa Vat Chompet</strong>|<strong>Phusalau</strong> – Chùa trên Núi Hủ Rượu|🏨 Nghỉ đêm tại Pakse",
  "day4.img": "https://images.trvl-media.com/place/2815/dd7a1c5d-8836-41a9-973b-11f19a4a4f09.jpg",
  "day4.title": "PAKSE → CAMPUCHIA → VIỆT NAM",
  "day4.route": "Pakse → Domcrolo & Vuenkham → Stungtreng → HCM",
  "day4.meals": "🥐 Ăn sáng KS|🍜 Cơm trưa Stungtreng",
  "day4.acts": "Ăn sáng tại khách sạn, làm thủ tục trả phòng, khởi hành về Campuchia|Đến cửa khẩu <strong>Domcrolo & Vuenkham</strong>|Dùng cơm trưa tại <strong>Stungtreng hoặc Kratier</strong>|Khởi hành về lại cửa khẩu Việt Nam|🎉 Kết thúc hành trình <strong>Tour Lào – Bolaven 4N3Đ</strong>",

  "price.label": "Giá Tour",
  "price.title": "Bảng Giá Rõ Ràng – Không Phí Ẩn",
  "price.sub": "Tất cả chi phí đã bao gồm trong giá tour.",
  "price.p1.title": "👶 Trẻ em dưới 2 tuổi",
  "price.p1.amt": "2,295,000₫",
  "price.p1.note": "30% giá người lớn • Ngủ chung giường",
  "price.p2.badge": "🌟 Phổ biến nhất",
  "price.p2.title": "🧑 Người lớn",
  "price.p2.amt": "7,650,000₫",
  "price.p2.note": "Giá thường • Khởi hành hàng tuần",
  "price.p2.list": "Xe đi thẳng VN → Campuchia → Lào|Khách sạn 4★ tại Lào (2 khách/phòng)|3 buffet sáng KS + 7 bữa ăn chính|Vé tham quan tất cả điểm trong tour|HDV tiếng Việt xuyên suốt|Bảo hiểm du lịch 200 triệu/khách|Quà tặng công ty + Khăn ướt",
  "price.p3.title": "🧒 Trẻ em 2–11 tuổi",
  "price.p3.amt": "5,737,500₫",
  "price.p3.note": "75% giá người lớn • Ngủ chung giường",
  "price.holiday": "🎉 Lễ 30/4/2026 đặc biệt: <strong>7,990,000₫</strong>/người lớn &nbsp;|&nbsp; Trẻ 2–11T: <strong>5,992,500₫</strong> &nbsp;|&nbsp; Trẻ &lt;2T: <strong>2,397,000₫</strong>",

  "sched.label": "Lịch Khởi Hành",
  "sched.title": "Ngày Khởi Hành 2026",
  "sched.table": "<tr><td>Tháng 4</td><td>30/04/2026 <span class=\"hol\">Lễ 30/4</span></td><td>7,990,000 ₫</td><td>5,992,500 ₫</td><td>2,397,000 ₫</td></tr><tr><td>Tháng 5</td><td>07, 14, 21, 28</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 6</td><td>04, 11, 18, 25</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 7</td><td>02, 09, 16, 23, 30</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 8</td><td>06, 13, 20, 27</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 9</td><td>10, 17, 24</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 10</td><td>01, 08, 15, 22, 29</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 11</td><td>05, 12, 19, 26</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr><tr><td>Tháng 12</td><td>03, 10, 17, 24</td><td>7,650,000 ₫</td><td>5,737,500 ₫</td><td>2,295,000 ₫</td></tr>",

  "svc.label": "Dịch vụ",
  "svc.title": "Bao gồm & Không bao gồm",
  "svc.inc.img": "https://datviettour.com.vn/uploads/images/tin-tuc-SEO-NN-chau-a/lao/danh-thang/bolaven-thoi-diem-dep-nhat.jpeg",
  "svc.inc.title": "✅ Giá tour bao gồm",
  "svc.inc.list": "Xe đi thẳng Việt Nam → Campuchia → Lào|Khách sạn tiêu chuẩn 4★ tại Lào (2 khách/phòng; lẻ nam/nữ ngủ phòng 3)|3 bữa buffet sáng tại KS + 7 bữa ăn chính theo chương trình|Vé vào cửa tất cả điểm tham quan theo chương trình|Hướng dẫn viên tiếng Việt đón tại Việt Nam|Quà tặng công ty + Khăn ướt|Bảo hiểm du lịch tối đa <strong>200,000,000 ₫/khách</strong>",
  "svc.exc.img": "https://vietkite.com.vn/wp-content/uploads/2024/12/pakse-song-mekong-lao.jpg",
  "svc.exc.title": "❌ Không bao gồm",
  "svc.exc.list": "Hộ chiếu phải còn hạn trên 6 tháng|Tip HDV & tài xế: <strong>5 USD/khách/ngày × 4 ngày = 20 USD</strong>|Visa Lào: <strong>40 USD</strong>/lần nhập cảnh (nếu cần)|Visa Cambodia: <strong>40 USD</strong>/lần nhập cảnh (nếu cần)|Visa tái nhập Việt Nam (nếu Visa Single)|Thuốc men, chi phí y tế cá nhân|Chèo thuyền Hồ Thateng và các chi phí tự túc khác|Chi phí phát sinh do bất khả kháng",
  "svc.pay.title": "📌 Quy trình thanh toán",
  "svc.pay.text": "Đặt cọc <strong>50%</strong> trước 10 ngày · Thanh toán còn lại trước <strong>7 ngày</strong> khởi hành · Hộ chiếu còn hạn 6+ tháng",

  "cpol.label": "Tiêu chuẩn trẻ em",
  "cpol.title": "Quy Định Trẻ Em",
  "cpol.1.title": "Dưới 2 tuổi",
  "cpol.1.text": "30% giá tour người lớn<br>Ngủ chung giường với người lớn<br>Có suất cháo + chi phí cửa khẩu",
  "cpol.2.title": "2 – 11 tuổi (ngủ chung)",
  "cpol.2.text": "75% giá tour người lớn<br>Ngủ chung giường với người lớn",
  "cpol.3.title": "2 – 11 tuổi (ngủ riêng)",
  "cpol.3.text": "100% giá tour người lớn<br>Có chế độ ngủ riêng",
  "cpol.4.title": "Từ 11 tuổi trở lên",
  "cpol.4.text": "100% giá tour người lớn<br>Có chế độ ngủ riêng",

  "cancel.label": "Điều kiện huỷ",
  "cancel.title": "Điều Kiện Huỷ Tour",
  "cancel.sub": "Không tính thứ 7, Chủ Nhật và ngày Lễ",
  "cancel.1.title": "Sau khi đăng ký",
  "cancel.1.text": "Phí phạt 50% tiền cọc",
  "cancel.2.title": "Trước 10 ngày",
  "cancel.2.text": "Phí phạt = 70% tổng giá tour (tính theo ngày làm việc)",
  "cancel.3.title": "Dưới 10 ngày",
  "cancel.3.text": "Phí phạt = 100% tổng giá trị chương trình",
  "cancel.4.title": "Tour Lễ/Tết – Trước 25 ngày",
  "cancel.4.text": "Cọc 50% khi đăng ký. Huỷ trước 25 ngày: 50% · Trước 20 ngày: 75% · Trước 15 ngày: 90%",

  "notes.label": "Lưu ý",
  "notes.title": "Lưu Ý Quan Trọng",
  "notes.1.title": "📋 Giấy tờ cần thiết",
  "notes.1.list": "Hộ chiếu còn hạn trên 6 tháng kể từ ngày về, còn nguyên vẹn|Giấy khai sinh (trẻ em đi cùng)|Visa Việt Nam nhập cảnh (hộ chiếu nước ngoài)|Giấy khám sức khoẻ (người trên 70 tuổi và phụ nữ mang thai dưới 30 tuần)",
  "notes.2.title": "👴 Quy định khách cao tuổi",
  "notes.2.list": "Từ 70–85 tuổi: gia đình phải cam kết tình trạng sức khoẻ với công ty|Từ 75 tuổi trở lên: cần giấy xác nhận đủ sức khoẻ của bác sĩ và phải có người thân dưới 60 tuổi đi kèm|Bảo hiểm không áp dụng cho khách trên 80 tuổi",
  "notes.3.title": "🚌 Về xe & đoàn",
  "notes.3.list": "Xe 16/29/45 chỗ tuỳ số lượng khách ngày khởi hành|Nếu số lượng khách là 13 người hoặc ít hơn, công ty có thể điều chỉnh sang xe 16 chỗ|Khách không được tách đoàn trong suốt chuyến tham quan",
  "notes.4.title": "⚠️ Lưu ý đặc biệt",
  "notes.4.list": "Khách đang đứng tên giấy phép kinh doanh cần hoàn thành nghĩa vụ thuế trước khi xuất cảnh|Khách mang Thẻ Xanh, Alien's Passport, Travel Document vui lòng báo trước khi đăng ký|Khách dưới 18 tuổi phải có bố mẹ hoặc người nhà đi kèm|Huỷ tour phải thông báo bằng văn bản/email – không chấp nhận qua điện thoại",

  "rev.label": "Đánh giá",
  "rev.title": "Khách hàng nói gì về VietKite?",
  "rev.1.text": "\"Tour Bolaven cực kỳ ấn tượng! Cao nguyên mát mẻ, thác nước đẹp tuyệt vời, đặc biệt là cà phê Paksong uống tại chỗ ngon hơn hẳn khi về nước. VietKite tổ chức rất chuyên nghiệp, hướng dẫn viên nhiệt tình và vui vẻ!\"",
  "rev.1.avatar": "https://ui-avatars.com/api/?name=Tran+Bao+Thy&background=1A7D3C&color=fff&size=44",
  "rev.1.name": "Trần Bảo Thy",
  "rev.1.loc": "TP.HCM · Tháng 6/2025",
  "rev.2.text": "\"Wat Phou thật sự không thua gì Angkor Wat. Không khí Bolaven mát mẻ như Đà Lạt, rất thích hợp cho gia đình có trẻ nhỏ. Xe thoải mái, cơm ngon, lịch trình hợp lý. Sẽ tiếp tục đặt tour VietKite!\"",
  "rev.2.avatar": "https://ui-avatars.com/api/?name=Ngo+Chi+Cuong&background=E8510A&color=fff&size=44",
  "rev.2.name": "Ngô Chí Cường",
  "rev.2.loc": "Bình Dương · Tháng 8/2025",
  "rev.3.text": "\"Thác Tad Fane đẹp không kém bất kỳ thác nào ở Việt Nam mà mình đã đi. Làng dân tộc Katu là trải nghiệm văn hoá rất độc đáo, không thể tìm được ở đâu khác. Cảm ơn VietKite đã tổ chức tour tuyệt vời!\"",
  "rev.3.avatar": "https://ui-avatars.com/api/?name=Lam+Dieu&background=7C3AED&color=fff&size=44",
  "rev.3.name": "Lâm Diệu",
  "rev.3.loc": "Đồng Nai · Tháng 9/2025",

  "book.label": "Thiết kế tour",
  "book.title": "Thiết Kế Tour Riêng Của Bạn",
  "book.sub": "Điền thông tin để VietKite tư vấn và báo giá trong vòng 24 giờ làm việc.",
  "book.bg": "https://vietkite.com.vn/wp-content/uploads/2024/12/tour-du-lich-lao-tu-tphcm.jpg",

  "footer.logo": "https://vietkite.com.vn/wp-content/uploads/2024/12/logo-cty-canh-dieu-viet-vietkite.jpg",
  "footer.brand": "VietKite Travel – Chuyên tổ chức tour du lịch quốc tế chuyên nghiệp, uy tín hơn 15 năm. Hành trình của bạn, niềm vui của chúng tôi.",
  "footer.col1.title": "Tour châu Á",
  "footer.col2.title": "Khám phá thêm",
  "footer.col3.title": "Liên hệ",
  "footer.contact": "<strong>CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ DU LỊCH VIETKITE</strong><br>🆔 <strong>MST:</strong> 0311304593<br>🌐 <a href=\"https://vietkite.com.vn\">vietkite.com.vn</a><br>✉️ <a href=\"mailto:info@vietkite.com.vn\">info@vietkite.com.vn</a><br>📍 <strong>VP 1:</strong> 276 Nơ Trang Long, P. 12, Q. Bình Thạnh, TP.HCM<br>📍 <strong>VP 2:</strong> 160/25/31 Bùi Đình Túy, P. 12, Q. Bình Thạnh, TP.HCM<br>🕐 T2–CN: 8:00 – 20:00",
  "footer.copy": "© 2026 VietKite Travel. GP LHQT: xxxx/2010/TCDL-GP LHQT",
  "footer.tag": "Thiết kế dành riêng cho VietKite ♥",

  "contact.phone": "0912992447",
  "contact.zalo": "https://zalo.me/0912992447",
  "contact.fb": "https://m.me/vietkitetravelhcm"
};
